import React from "react";
import Head from "next/head";
import Container from "react-bootstrap/Container";
import {Navbar} from "./Navbar";

interface LayoutProps {
  children: React.ReactElement;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Rayzor_Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main text-dark pb-3">
        <Navbar />

        <Container>{children}</Container>
      </main>
    </>
  );
};

export default Layout;
